In [6]:
import numpy as np
#Make new array
array1=np.array([1,2,3])
print(type(array1))

<class 'numpy.ndarray'>


In [19]:
#Make 2D numpy array
array2=np.array([[1.1,2,3],[3,4,5],[6,7,8]],dtype="int32")
array2.shape
array2.dtype


dtype('int32')

In [23]:
zeroarray=np.zeros((6,6))
print(zeroarray)
onesarray=np.ones((5,4))
print(onesarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
array3=np.array([[1,2,3],[3,4,5],[5,6,7]])
multiply=np.dot(array3,array3)
print(multiply)

[[22 28 34]
 [40 52 64]
 [58 76 94]]
