In [1]:
import numpy as np
list=[[1,2,5,7],[5,7,8,9],[5,6,7,10]]
array1=np.array(list,dtype="float64")
print("Array1=")
print(array1)
print(f"Shape of array is:{array1.shape}")
print(f"The data type of elements of array is:{array1.dtype}")
print(f"The type of variable array1 is {type(array1)}")

Array1=
[[ 1.  2.  5.  7.]
 [ 5.  7.  8.  9.]
 [ 5.  6.  7. 10.]]
Shape of array is:(3, 4)
The data type of elements of array is:float64
The type of variable array1 is <class 'numpy.ndarray'>


In [2]:
array2=np.zeros((4,3))
print(array2)
print(f"THe data type of array 1 is {array2.dtype}")
print(f"THe type of variable array2 is {type(array2)}")
print(f"THe shape of array2 is {array2.shape}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
THe data type of array 1 is float64
THe type of variable array2 is <class 'numpy.ndarray'>
THe shape of array2 is (4, 3)


In [3]:
no=int(input("Enter size of zero square matrix:"))
array3=np.zeros((no,no))
print("The array3 is:")
print(array3)
print(f"The data type of array3 is {array3.dtype}")
print(f"THe variable array3 is {type(array3)}")
print(f"The size of array3 is {array3.shape}")


Enter size of zero square matrix:2
The array3 is:
[[0. 0.]
 [0. 0.]]
The data type of array3 is float64
THe variable array3 is <class 'numpy.ndarray'>
The size of array3 is (2, 2)


In [4]:
array4=np.empty((6,6))
print(f"The empty array is:{array4}")
print(f"The size of the array is: {array4.shape} ")
print(f"The variable array4 is : {type(array4)}")
print(f"Data type for array4 is:{array4.dtype}")


The empty array is:[[ 3.52262572e-303  1.33360298e+241  1.16497569e-310  3.42196482e-210
   6.67268208e-313  4.57400437e-308]
 [ 1.33360306e+241  1.92549898e-310  1.77678572e-176  7.94587955e-313
   6.24280976e-308  1.33360308e+241]
 [ 2.63169918e-310  2.48721655e-075  1.04922745e-312  2.88067937e+214
  -4.55907831e-239  4.27777278e-270]
 [ 7.87691239e-251  4.78064292e-299  5.07928728e-299  4.78064292e-299
   4.78064748e-299  5.07928728e-299]
 [ 4.78064292e-299  4.78064292e-299  4.78064748e-299  3.03453759e-269
   3.57057593e-241  2.46377988e-269]
 [ 1.38470334e-259  1.72779501e-260  3.60254708e-269  1.79117837e-259
   7.58369397e-269  3.05783956e-051]]
The size of the array is: (6, 6) 
The variable array4 is : <class 'numpy.ndarray'>
Data type for array4 is:float64


In [5]:
nos=int(input("Enter size of matrix with 1s:"))
array5=np.ones((nos,nos))
print(f"Array5 is:\n{array5}")
print(f"Size of array5 is:{array5.shape}")
print(f"datatype of array5 is:{array5.dtype}")

Enter size of matrix with 1s:5
Array5 is:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Size of array5 is:(5, 5)
datatype of array5 is:float64


In [6]:
array6=np.arange(7)
array7=np.arange(7,dtype="float64")
array8=np.arange(2,2.55,0.1)
array9=np.arange(10,60,10)
print(f"array6=\n{array6} \narray7=\n{array7} \narray8=\n{array8} \narray9=\n{array9}")

array6=
[0 1 2 3 4 5 6] 
array7=
[0. 1. 2. 3. 4. 5. 6.] 
array8=
[2.  2.1 2.2 2.3 2.4 2.5] 
array9=
[10 20 30 40 50]


In [7]:
array10=np.linspace(1,4,6)
print(array10)

[1.  1.6 2.2 2.8 3.4 4. ]


In [8]:
array11=np.linspace(0,100,5)
print(array11)

[  0.  25.  50.  75. 100.]
