In [3]:
import numpy as np
#reshape into new shape
array1=np.array([4,5,7,5,6,7,8,9,6])
print(array1.reshape(3,3))
#best way to do is:
array1=np.reshape(array1,(3,3))
print(array1)

[[4 5 7]
 [5 6 7]
 [8 9 6]]
[[4 5 7]
 [5 6 7]
 [8 9 6]]


In [15]:
#argsort,argmin,argmax: sorting ko position dene function,argmin: least element ko position, argmax: maxm element ko function
array2=np.array([4,5,7,5,0,6,7,8,9,9,6,0])
print(np.argsort(array2))
print(np.argmin(array2))
print(np.argmax(array2))
array3=np.reshape(array2,(4,3))
#2D array ma argsort use gareko. axis 0 or 1 ma argsort use garna milcha
print(array3)
print(np.argsort(array3,axis=1))
print(np.argsort(array3,axis=0))
print(np.argmin(array3,axis=1))
print(np.argmin(array3,axis=0))
print(np.argmax(array3,axis=1))
print(np.argmax(array3,axis=0))



[0 1 0 2]
[0 1 3]
[2 2 2 0]
[3 2 2]


In [23]:
#find root of equation: x2-4x+4 and x4-11x3+9x2+11x-10
coff1=np.array([1,-4,4])
print(np.roots(coff1))
coff2=np.array([1,-11,9,11,-10])
print(np.roots(coff2))

[2. 2.]
[10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]
